# Generated by Django 3.2.4 on 2021-06-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clinic'),
        ),
    ]
