# Generated by Django 3.2.4 on 2021-06-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_appointment_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'date')},
        ),
    ]
