# Generated by Django 3.2.4 on 2021-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210628_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(null=True, to='project.Specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
